### ISSUE TITLE
Module name

### ISSUE THREAD

**Issue by RomkeVdMeulen** [heruan/aurelia-property-injection#3]
A little detail that caught my attention: `aurelia-inject-properties` as a module name doesn't match the naming of core aurelia modules. It contains a verb, while core modules are named for the concept they provide.

Perhaps it should be named `aurelia-property-injection` instead?

**Comment by heruan** [comment]
I agree. @EisenbergEffect do you think `aurelia-property-injection` could fit Aurelia's module naming conventions?

**Comment by EisenbergEffect** [comment]
@heruan The second name recommended by @RomkeVdMeulen is probably better. It is your plugin, so it's ultimately up to you though. Once you have things where you want them, be sure to submit a PR to the registry repo to add your plugin to our list. In the near future we'll publishing these on the site :)

**Comment by heruan** [comment]
Module renamed to `aurelia-property-injection`.
