### ISSUE TITLE
Suggestion: always call afterConstructor

### ISSUE THREAD

**Issue by RomkeVdMeulen** [heruan/aurelia-property-injection#4]
Currently the `afterConstructor` hook is only called on classes that have injected properties. I can certainly understand why you'd write it that way. But as a user I would expect that if a hook called `afterConstructor` exists, it would always be called, even on classes that don't have injected properties.

**Comment by RomkeVdMeulen** [comment]
To illustrate, I'm trying to do this in my project:

```ts
export abstract class InitBase<InitResolveType> {

	private initPromise: Promise<InitResolveType>;

	private afterConstructor() {
		this.initPromise = this.init();
	}

	public waitForInit(): Promise<InitResolveType> {
		return this.initPromise;
	}

	protected abstract init(): Promise<InitResolveType>;
}

export class MyAutoInitService extends InitBase<MyUserDetails> {
	protected init(): Promise<InitResolveType> {
		return new Promise(resolve => {
			// some extensive calculation
			resolve(myUserDetails);
		});
	}
}

export class MyComponent {
	@autoinject
	private service: MyAutoInitService;

	private myUser: MyUserDetails;

	afterConstructor() {
		this.service.waitForInit().then(myUser => this.myUser = myUser);
	}
}
```

The above works if `MyAutoInitService` has injected properties, otherwise it doesn't.

**Comment by heruan** [comment]
Yes, the hook is called only when the class has injected properties; that was a performance choice when the feature was being developed in core, but now I'd like to make it configurable.

**Comment by heruan** [comment]
I'm closing this since from version 0.4.0 property injection will make injected properties available in constructors, thus leaving the hook without any purpose in the scope of this plugin.
